apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper
spec:
  type : NodePort
  ports:
  - name: zookeeper-port
    port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: kafka
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        ports:
        - containerPort: 2181
        volumeMounts:
        - name: datadir
          mountPath: "/var/lib/zookeeper"
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi