apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka
spec:
  serviceName: kafka-broker
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
        - name: kafka-broker       
          image: ksgregistry.azurecr.io/wk-kafka:latest
          imagePullPolicy: Always     
          env:
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092,SSL://:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://20.4.99.189:9092,SSL://20.4.99.189:9093
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 10.0.254.79:2181
            - name: KAFKA_CREATE_TOPICS
              value: "test-topic:1:1"
            - name: KAFKA_BROKER_ID
              value: "1"
            # - name: KAFKA_SECURITY_INTER_BROKER_PROTOCOL
            #   value: PLAINTEXT
            # - name: KAFKA_SSL_CLIENT_AUTH
            #   value: required
            - name: KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              value: 
            - name: KAFKA_SECURITY_PROVIDERS
              value: com.microsoft.kafkaspiffe.KafkaSpiffeSecurityProvider
            - name: KAFKA_SSL_TRUSTMANAGER_ALGORITHM
              value: Spiffe
            - name: KAFKA_SSL_KEYMANAGER_ALGORITHM
              value: Spiffe
            - name: KAFKA_SPIFFE_ID
              value: spiffe://nostak.org/ns/kafka/sa/default
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:/run/spire/sockets/agent.sock
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
          # ports:
          #   - containerPort: 9093
          #     name: ssl
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory